services:
  app:
    build: .
    ports:
      - "80:8000"
    env_file:
      - .env
    command: ["npm", "start"]
    depends_on:
      - redis-persistent
      - redis-cache

  redis-persistent:
    image: redis/redis-stack:latest
    ports:
      - "6380:6379"
    environment:
      - REDIS_ARGS=--appendonly yes --maxmemory 1gb
    volumes:
      - ./local-data:/data

  redis-cache:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_ARGS=--maxmemory 1gb

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
